version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres/transfers_db
      POSTGRES_USER: vrtn_user
      POSTGRES_PASSWORD: vrtn_password
      POSTGRES_DB: transfers_db
    ports:
      - "5432:5432"

  pet-backend-users:
    build:
      context: ./pet-backend-users
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  pet-backend-accounts:
    build:
      context: ./pet-backend-accounts
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  pet-backend-transfers:
    build:
      context: ./pet-backend-transfers
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka

  pet-backend-history:
    build:
      context: ./pet-backend-history
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1